global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'consumer'
    static_configs:
      - targets: ['host.docker.internal:2112']
